
name: deploy-to-production

services:

  nginx:
    build:
      context: ./nginx
    ports:
      - 8080:8000
      - 8443:443
    depends_on:
      - web
    volumes:
    - ./letsencrypt:/etc/letsencrypt
    restart: "always"

  web:
    build: ./app
    #command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    #expose:
     # - 8000
    env_file:
      - ./app/.env.dev

networks:
  net:
    name: deploy-to-production
